---
name: "Setup the environment"
description: "This action sets up python and poetry as well as some caches to speed up the build process."
inputs:
  python-version:
    description: "Python version that will be deployed"
    required: false
    default: "3.9"

runs:
  using: "composite"
  steps:
    - name: "Set up Python"
      uses: "actions/setup-python@v4"
      id: "python-setup"
      with:
        python-version: "${{ inputs.python-version }}"
    - name: "Setup Build Environment Cache"
      uses: "actions/cache@v3"
      id: "cached-env"
      with:
        path: |
          ~/.local/share/pypoetry
          ~/.local/bin
        key: "${{ runner.os }}-build-env-${{ inputs.python-version }}-${{ hashFiles('./poetry.lock') }}"
    - name: "Setup environment"
      uses: "networktocode/gh-action-setup-poetry-environment@v4"
      with:
        python-version: "${{ inputs.python-version }}"
